require 'rea/robot/commands/move_command'
require 'rea/robot/commands/report_command'
require 'rea/robot/commands/left_command'
require 'rea/robot/commands/right_command'
require 'rea/robot/commands/place_command'
