require 'rea/robot/domain/board_cell_factory'
require 'rea/robot/domain/direction_factory'
require 'rea/robot/domain/rotation'
require 'rea/robot/domain/robot'
require 'rea/robot/domain/board'
require 'rea/robot/domain/thing'
require 'rea/robot/domain/thing_on_cell'
require 'rea/robot/domain/things_on_board_collection'
